# Generated by Django 3.2.13 on 2023-02-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
